### imports

In [17]:
import pandas as pd
import sqlite3

In [19]:
db_path = "data/police_data.db"
conn = sqlite3.connect(db_path)

### light eda

In [29]:
#display all columns
coldf = pd.read_sql("PRAGMA table_info(street_crimes);", conn)
display(coldf[['name']])

#count all rows
total_rows = pd.read_sql("SELECT COUNT(*) as total FROM street_crimes;", conn).iloc[0,0]
print(f'total rows {total_rows}')

#check for null rows and calculate percentage per column 
null_query = """
SELECT 
    COUNT(*) - COUNT("Crime ID") as missing_crime_id,
    COUNT(*) - COUNT("LSOA code") as missing_lsoa,
    COUNT(*) - COUNT(Longitude) as missing_longitude,
    COUNT(*) - COUNT("Last outcome category") as missing_outcome
FROM street_crimes;
"""
null_df = pd.read_sql(null_query, conn)
null_percentages = (null_df / total_rows) * 100
display(null_percentages.round(2).astype(str) + '%')

#distribution of crime type
crime_type_query = """
SELECT "Crime type", COUNT(*) as incident_count 
FROM street_crimes 
GROUP BY "Crime type" 
ORDER BY incident_count DESC;
"""
crime_df = pd.read_sql(crime_type_query, conn)
crime_df['percentage'] = ((crime_df['incident_count'] / total_rows) * 100).round(2)
display(crime_df)

## outcomes 
outcome_query = """
SELECT "Last outcome category", COUNT(*) as count 
FROM street_crimes 
GROUP BY "Last outcome category" 
ORDER BY count DESC;
"""
outcome_df = pd.read_sql(outcome_query, conn)
display(outcome_df)

london_query = """
SELECT "
london_df = pd.


conn.close()

                     name
0                Crime ID
1                   Month
2             Reported by
3            Falls within
4               Longitude
5                Latitude
6                Location
7               LSOA code
8               LSOA name
9              Crime type
10  Last outcome category
11                Context

total rows 12259171

  missing_crime_id missing_lsoa missing_longitude missing_outcome
0           16.39%        3.75%             1.42%          17.98%

                      Crime type  incident_count  percentage
0   Violence and sexual offences         4257818       34.73
1          Anti-social behaviour         1968048       16.05
2                    Shoplifting         1011508        8.25
3      Criminal damage and arson          907180        7.40
4                    Other theft          842805        6.87
5                   Public order          840265        6.85
6                  Vehicle crime          652899        5.33
7                       Burglary          466591        3.81
8                          Drugs          408812        3.33
9                    Other crime          268091        2.19
10         Theft from the person          253730        2.07
11                       Robbery          157370        1.28
12         Possession of weapons          115138        0.94
13                 Bicycle theft          108916        0.89

                                Last outcome category    count
0                         Unable to prosecute suspect  3765567
1       Investigation complete; no suspect identified  3700292
2                                                None  2204422
3                           Status update unavailable   687979
4                            Court result unavailable   502705
5                                 Under investigation   456820
6                                    Local resolution   292467
7                              Awaiting court outcome   276004
8          Action to be taken by another organisation   139017
9                            Offender given a caution    73967
10  Further investigation is not in the public int...    68430
11        Formal action is not in the public interest    40602
12       Further action is not in the public interest    36469
13            Suspect charged as part of another case     7178
14                      Offender given penalty notice     6644
15          Offender given a drugs possession warning      608